export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const REGISTER_USER_BEGINS = "REGISTER_USER_BEGINS";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGINS = "LOGIN_USER_BEGINS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const VERIFICATION_BEGINS = "VERIFICATION_BEGINS";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_ERROR = "VERIFICATION_ERROR";

export const GET_ALL_PRODUCTS_BEGINS = "GET_ALL_PRODUCTS_BEGINS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

export const GET_SINGLE_PRODUCT_BEGINS = "GET_ALL_PRODUCT_BEGINS";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_ALL_PRODUCT_ERROR";

export const UPLOAD_IMAGE_BEGINS = "UPLOAD_IMAGE_BEGINS";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

export const CREATE_PRODUCT_BEGINS = "CREATE_PRODUCT_BEGINS";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";

export const UPDATE_PRODUCT_BEGINS = "UPDATE_PRODUCT_BEGINS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

export const DELETE_PRODUCT_BEGIN = "DELETE_PRODUCT_BEGIN";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const SET_EDIT_ID = "SET_EDIT_ID";

export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_ITEM_QUANTITY_IN_CART = "UPDATE_ITEM_QUANTITY_IN_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const RESET_CART = "RESET_CART";

export const UPDATE_TOTAL_AMOUNT = "UPDATE_TOTAL_AMOUNT";

export const UPDATE_ORDER_BEGINS = "UPADTE_ORDER_BEGINS";
export const UPDATE_ORDER_SUCCESS = "UPADTE_ORDER_SUCCESS";
export const UPDATE_ORDER_ERROR = "UPADTE_ORDER_ERROR";

export const CREATE_ORDER_BEGINS = "CREATE_ORDER_BEGINS";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const FETCH_ORDERED_ITEM_BEGINS = "FETCH_ORDERED_ITEM_BEGINS";
export const FETCH_ORDERED_ITEM_SUCCESS = "FETCH_ORDERED_ITEM_SUCCESS";
export const FETCH_ORDERED_ITEM_ERROR = "FETCH_ORDERED_ITEM_ERROR";

export const FETCH_SINGLE_ORDER_BEGINS = "FETCH_SINGLE_ORDER_BEGINS";
export const FETCH_SINGLE_ORDER_SUCCESS = "FETCH_SINGLE_ORDER_SUCCESS";
export const FETCH_SINGLE_ORDER_ERROR = "FETCH_SINGLE_ORDER_ERROR";

export const CANCEL_ORDER_BEGINS = "CANCEL_ORDER_BEGINS";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_ERROR = "CANCEL_ORDER_ERROR";

export const CREATE_REVIEW_BEGINS = "CREATE_REVIEW_BEGINS";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_ERROR = "CREATE_REVIEW_ERROR";

export const GET_SINGLE_PRODUCT_REVIEW_BEGINS =
  "GET_SINGLE_PRODUCT_REVIEW_BEGINS";
export const GET_SINGLE_PRODUCT_REVIEW_SUCCESS =
  "GET_SINGLE_PRODUCT_REVIEW_SUCCESS";
export const GET_SINGLE_PRODUCT_REVIEW_ERROR =
  "GET_SINGLE_PRODUCT_REVIEW_ERROR";

export const DELETE_REVIEW_BEGINS = "DELETE_REVIEW_BEGINS";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_ERROR = "DELETE_REVIEW_ERROR";

export const SET_EDIT_REVIEW = "SET_EDIT_REVIEW";

export const EDIT_REVIEW_BEGINS = "EDIT_REVIEW_BEGINS";
export const EDIT_REVIEW_SUCCESS = "EDIT_REVIEW_SUCCESS";
export const EDIT_REVIEW_ERROR = "EDIT_REVIEW_ERROR";

export const CHANGE_PAGE = "CHANGE_PAGE";
export const TOGGLE_MENU = "TOGGLE_MENU";
